SET NAMES UTF8;
SET SQL DIALECT 3;
CONNECT 'localhost/3050:/var/lib/firebird/data/sklad-system/sklad_system.fdb' USER 'SYSDBA' PASSWORD '7517';
SET AUTODDL ON;

/* WAREHOUSE */
CREATE TABLE WAREHOUSE (
    ID INTEGER NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(250),
    IS_ACTIVE SMALLINT DEFAULT 1 NOT NULL);

/* PRODUCT */
CREATE TABLE PRODUCT (
    ID INTEGER NOT NULL,
    ARTICLE VARCHAR(50) NOT NULL,
    BARCODE VARCHAR(50),
    NAME VARCHAR(150) NOT NULL,
    CATEGORY_ID INTEGER NOT NULL,
    UNIT_ID INTEGER NOT NULL,
    PRICE NUMERIC(14,2) DEFAULT 0 NOT NULL,
    MIN_STOCK NUMERIC(14,3) DEFAULT 0 NOT NULL,
    IS_ACTIVE SMALLINT DEFAULT 1 NOT NULL,
    NOTES VARCHAR(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);

/* STOCK_DOCUMENT_ITEM */
CREATE TABLE STOCK_DOCUMENT_ITEM (
    ID INTEGER NOT NULL,
    DOCUMENT_ID INTEGER NOT NULL,
    PRODUCT_ID INTEGER NOT NULL,
    SOURCE_LOCATION_ID INTEGER,
    TARGET_LOCATION_ID INTEGER,
    QUANTITY NUMERIC(14,3) NOT NULL,
    PRICE NUMERIC(14,2) DEFAULT 0 NOT NULL,
    NOTES VARCHAR(250));

/* APP_ROLE */
CREATE TABLE APP_ROLE (
    ID INTEGER NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(250));

/* PRODUCT_CATEGORY */
CREATE TABLE PRODUCT_CATEGORY (
    ID INTEGER NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    PARENT_ID INTEGER,
    DESCRIPTION VARCHAR(250));

/* COUNTERPARTY */
CREATE TABLE COUNTERPARTY (
    ID INTEGER NOT NULL,
    NAME VARCHAR(150) NOT NULL,
    PARTY_TYPE VARCHAR(20) NOT NULL,
    PHONE VARCHAR(30),
    EMAIL VARCHAR(120),
    ADDRESS VARCHAR(250),
    IS_ACTIVE SMALLINT DEFAULT 1 NOT NULL);

/* STORAGE_LOCATION */
CREATE TABLE STORAGE_LOCATION (
    ID INTEGER NOT NULL,
    WAREHOUSE_ID INTEGER NOT NULL,
    CODE VARCHAR(30) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    CAPACITY NUMERIC(14,3),
    IS_ACTIVE SMALLINT DEFAULT 1 NOT NULL);

/* MEASURE_UNIT */
CREATE TABLE MEASURE_UNIT (
    ID INTEGER NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    SHORT_NAME VARCHAR(20) NOT NULL);

/* STOCK_DOCUMENT */
CREATE TABLE STOCK_DOCUMENT (
    ID INTEGER NOT NULL,
    DOC_NUMBER VARCHAR(50) NOT NULL,
    DOC_TYPE VARCHAR(20) NOT NULL,
    DOC_STATUS VARCHAR(20) DEFAULT 'DRAFT' NOT NULL,
    DOC_DATE DATE DEFAULT CURRENT_DATE NOT NULL,
    WAREHOUSE_ID INTEGER NOT NULL,
    COUNTERPARTY_ID INTEGER,
    CREATED_BY INTEGER NOT NULL,
    NOTES VARCHAR(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PARTNER_NAME VARCHAR(150));

/* APP_USER */
CREATE TABLE APP_USER (
    ID INTEGER NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    FULL_NAME VARCHAR(120) NOT NULL,
    ROLE_ID INTEGER NOT NULL,
    IS_ACTIVE SMALLINT DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);

/* BI_APP_USER */
CREATE OR ALTER TRIGGER BI_APP_USER
	FOR APP_USER BEFORE INSERT
AS BEGIN END;

/* BI_STORAGE_LOCATION */
CREATE OR ALTER TRIGGER BI_STORAGE_LOCATION
	FOR STORAGE_LOCATION BEFORE INSERT
AS BEGIN END;

/* BI_WAREHOUSE */
CREATE OR ALTER TRIGGER BI_WAREHOUSE
	FOR WAREHOUSE BEFORE INSERT
AS BEGIN END;

/* BI_STOCK_DOC_ITEM */
CREATE OR ALTER TRIGGER BI_STOCK_DOC_ITEM
	FOR STOCK_DOCUMENT_ITEM BEFORE INSERT
AS BEGIN END;

/* BI_COUNTERPARTY */
CREATE OR ALTER TRIGGER BI_COUNTERPARTY
	FOR COUNTERPARTY BEFORE INSERT
AS BEGIN END;

/* BI_STOCK_DOCUMENT */
CREATE OR ALTER TRIGGER BI_STOCK_DOCUMENT
	FOR STOCK_DOCUMENT BEFORE INSERT
AS BEGIN END;

/* BI_MEASURE_UNIT */
CREATE OR ALTER TRIGGER BI_MEASURE_UNIT
	FOR MEASURE_UNIT BEFORE INSERT
AS BEGIN END;

/* BI_APP_ROLE */
CREATE OR ALTER TRIGGER BI_APP_ROLE
	FOR APP_ROLE BEFORE INSERT
AS BEGIN END;

/* BI_PRODUCT */
CREATE OR ALTER TRIGGER BI_PRODUCT
	FOR PRODUCT BEFORE INSERT
AS BEGIN END;

/* BI_PRODUCT_CATEGORY */
CREATE OR ALTER TRIGGER BI_PRODUCT_CATEGORY
	FOR PRODUCT_CATEGORY BEFORE INSERT
AS BEGIN END;

/* IX_STOCK_DOC_STATUS */
CREATE INDEX IX_STOCK_DOC_STATUS ON STOCK_DOCUMENT (DOC_STATUS);

/* IX_STOCK_DOC_DATE */
CREATE INDEX IX_STOCK_DOC_DATE ON STOCK_DOCUMENT (DOC_DATE);

/* IX_PRODUCT_NAME */
CREATE INDEX IX_PRODUCT_NAME ON PRODUCT (NAME);

/* IX_COUNTERPARTY_NAME */
CREATE INDEX IX_COUNTERPARTY_NAME ON COUNTERPARTY (NAME);

/* GEN_COUNTERPARTY_ID */
CREATE OR ALTER SEQUENCE GEN_COUNTERPARTY_ID START WITH 1 INCREMENT BY 1;

/* GEN_STOCK_DOC_ITEM_ID */
CREATE OR ALTER SEQUENCE GEN_STOCK_DOC_ITEM_ID START WITH 1 INCREMENT BY 1;

/* GEN_PRODUCT_ID */
CREATE OR ALTER SEQUENCE GEN_PRODUCT_ID START WITH 1 INCREMENT BY 1;

/* GEN_STOCK_BALANCE_ID */
CREATE OR ALTER SEQUENCE GEN_STOCK_BALANCE_ID START WITH 1 INCREMENT BY 1;

/* GEN_WAREHOUSE_ID */
CREATE OR ALTER SEQUENCE GEN_WAREHOUSE_ID START WITH 1 INCREMENT BY 1;

/* GEN_STOCK_DOCUMENT_ID */
CREATE OR ALTER SEQUENCE GEN_STOCK_DOCUMENT_ID START WITH 1 INCREMENT BY 1;

/* GEN_STOCK_MOVEMENT_ID */
CREATE OR ALTER SEQUENCE GEN_STOCK_MOVEMENT_ID START WITH 1 INCREMENT BY 1;

/* GEN_APP_ROLE_ID */
CREATE OR ALTER SEQUENCE GEN_APP_ROLE_ID START WITH 1 INCREMENT BY 1;

/* GEN_APP_USER_ID */
CREATE OR ALTER SEQUENCE GEN_APP_USER_ID START WITH 1 INCREMENT BY 1;

/* GEN_PRODUCT_CATEGORY_ID */
CREATE OR ALTER SEQUENCE GEN_PRODUCT_CATEGORY_ID START WITH 1 INCREMENT BY 1;

/* GEN_MEASURE_UNIT_ID */
CREATE OR ALTER SEQUENCE GEN_MEASURE_UNIT_ID START WITH 1 INCREMENT BY 1;

/* GEN_STORAGE_LOCATION_ID */
CREATE OR ALTER SEQUENCE GEN_STORAGE_LOCATION_ID START WITH 1 INCREMENT BY 1;

/* BI_APP_USER */
CREATE OR ALTER TRIGGER BI_APP_USER FOR APP_USER
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = GEN_ID(GEN_APP_USER_ID, 1);
END;

/* BI_STORAGE_LOCATION */
CREATE OR ALTER TRIGGER BI_STORAGE_LOCATION FOR STORAGE_LOCATION
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = GEN_ID(GEN_STORAGE_LOCATION_ID, 1);
END;

/* BI_WAREHOUSE */
CREATE OR ALTER TRIGGER BI_WAREHOUSE FOR WAREHOUSE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = GEN_ID(GEN_WAREHOUSE_ID, 1);
END;

/* BI_STOCK_DOC_ITEM */
CREATE OR ALTER TRIGGER BI_STOCK_DOC_ITEM FOR STOCK_DOCUMENT_ITEM
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = GEN_ID(GEN_STOCK_DOC_ITEM_ID, 1);
END;

/* BI_COUNTERPARTY */
CREATE OR ALTER TRIGGER BI_COUNTERPARTY FOR COUNTERPARTY
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = GEN_ID(GEN_COUNTERPARTY_ID, 1);
END;

/* BI_STOCK_DOCUMENT */
CREATE OR ALTER TRIGGER BI_STOCK_DOCUMENT FOR STOCK_DOCUMENT
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = GEN_ID(GEN_STOCK_DOCUMENT_ID, 1);
END;

/* BI_MEASURE_UNIT */
CREATE OR ALTER TRIGGER BI_MEASURE_UNIT FOR MEASURE_UNIT
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = GEN_ID(GEN_MEASURE_UNIT_ID, 1);
END;

/* BI_APP_ROLE */
CREATE OR ALTER TRIGGER BI_APP_ROLE FOR APP_ROLE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = GEN_ID(GEN_APP_ROLE_ID, 1);
END;

/* BI_PRODUCT */
CREATE OR ALTER TRIGGER BI_PRODUCT FOR PRODUCT
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = GEN_ID(GEN_PRODUCT_ID, 1);
END;

/* BI_PRODUCT_CATEGORY */
CREATE OR ALTER TRIGGER BI_PRODUCT_CATEGORY FOR PRODUCT_CATEGORY
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = GEN_ID(GEN_PRODUCT_CATEGORY_ID, 1);
END;

/* WAREHOUSE.PK_WAREHOUSE */
ALTER TABLE WAREHOUSE
ADD CONSTRAINT PK_WAREHOUSE PRIMARY KEY (ID);

/* PRODUCT.PK_PRODUCT */
ALTER TABLE PRODUCT
ADD CONSTRAINT PK_PRODUCT PRIMARY KEY (ID);

/* STOCK_DOCUMENT_ITEM.PK_STOCK_DOC_ITEM */
ALTER TABLE STOCK_DOCUMENT_ITEM
ADD CONSTRAINT PK_STOCK_DOC_ITEM PRIMARY KEY (ID);

/* APP_ROLE.PK_APP_ROLE */
ALTER TABLE APP_ROLE
ADD CONSTRAINT PK_APP_ROLE PRIMARY KEY (ID);

/* PRODUCT_CATEGORY.PK_PRODUCT_CATEGORY */
ALTER TABLE PRODUCT_CATEGORY
ADD CONSTRAINT PK_PRODUCT_CATEGORY PRIMARY KEY (ID);

/* COUNTERPARTY.PK_COUNTERPARTY */
ALTER TABLE COUNTERPARTY
ADD CONSTRAINT PK_COUNTERPARTY PRIMARY KEY (ID);

/* STORAGE_LOCATION.PK_STORAGE_LOCATION */
ALTER TABLE STORAGE_LOCATION
ADD CONSTRAINT PK_STORAGE_LOCATION PRIMARY KEY (ID);

/* MEASURE_UNIT.PK_MEASURE_UNIT */
ALTER TABLE MEASURE_UNIT
ADD CONSTRAINT PK_MEASURE_UNIT PRIMARY KEY (ID);

/* STOCK_DOCUMENT.PK_STOCK_DOCUMENT */
ALTER TABLE STOCK_DOCUMENT
ADD CONSTRAINT PK_STOCK_DOCUMENT PRIMARY KEY (ID);

/* APP_USER.PK_APP_USER */
ALTER TABLE APP_USER
ADD CONSTRAINT PK_APP_USER PRIMARY KEY (ID);

/* WAREHOUSE.UQ_WAREHOUSE_NAME */
ALTER TABLE WAREHOUSE
ADD CONSTRAINT UQ_WAREHOUSE_NAME UNIQUE (NAME);

/* PRODUCT.UQ_PRODUCT_ARTICLE */
ALTER TABLE PRODUCT
ADD CONSTRAINT UQ_PRODUCT_ARTICLE UNIQUE (ARTICLE);

/* PRODUCT.UQ_PRODUCT_BARCODE */
ALTER TABLE PRODUCT
ADD CONSTRAINT UQ_PRODUCT_BARCODE UNIQUE (BARCODE);

/* APP_ROLE.UQ_APP_ROLE_NAME */
ALTER TABLE APP_ROLE
ADD CONSTRAINT UQ_APP_ROLE_NAME UNIQUE (NAME);

/* PRODUCT_CATEGORY.UQ_PRODUCT_CATEGORY_NAME */
ALTER TABLE PRODUCT_CATEGORY
ADD CONSTRAINT UQ_PRODUCT_CATEGORY_NAME UNIQUE (NAME);

/* STORAGE_LOCATION.UQ_ST_LOC_CODE */
ALTER TABLE STORAGE_LOCATION
ADD CONSTRAINT UQ_ST_LOC_CODE UNIQUE (WAREHOUSE_ID, CODE);

/* MEASURE_UNIT.UQ_MEASURE_UNIT_NAME */
ALTER TABLE MEASURE_UNIT
ADD CONSTRAINT UQ_MEASURE_UNIT_NAME UNIQUE (NAME);

/* MEASURE_UNIT.UQ_MEASURE_UNIT_SHORT */
ALTER TABLE MEASURE_UNIT
ADD CONSTRAINT UQ_MEASURE_UNIT_SHORT UNIQUE (SHORT_NAME);

/* STOCK_DOCUMENT.UQ_STOCK_DOC_NUMBER */
ALTER TABLE STOCK_DOCUMENT
ADD CONSTRAINT UQ_STOCK_DOC_NUMBER UNIQUE (DOC_NUMBER);

/* APP_USER.UQ_APP_USER_USERNAME */
ALTER TABLE APP_USER
ADD CONSTRAINT UQ_APP_USER_USERNAME UNIQUE (USERNAME);

/* PRODUCT.FK_PRODUCT_CATEGORY */
ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES PRODUCT_CATEGORY (ID);

/* PRODUCT.FK_PRODUCT_UNIT */
ALTER TABLE PRODUCT
ADD CONSTRAINT FK_PRODUCT_UNIT FOREIGN KEY (UNIT_ID) REFERENCES MEASURE_UNIT (ID);

/* STOCK_DOCUMENT_ITEM.FK_ST_DOC_ITEM_DOC */
ALTER TABLE STOCK_DOCUMENT_ITEM
ADD CONSTRAINT FK_ST_DOC_ITEM_DOC FOREIGN KEY (DOCUMENT_ID) REFERENCES STOCK_DOCUMENT (ID);

/* STOCK_DOCUMENT_ITEM.FK_ST_DOC_ITEM_PROD */
ALTER TABLE STOCK_DOCUMENT_ITEM
ADD CONSTRAINT FK_ST_DOC_ITEM_PROD FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID);

/* STOCK_DOCUMENT_ITEM.FK_ST_DOC_ITEM_SRC_LOC */
ALTER TABLE STOCK_DOCUMENT_ITEM
ADD CONSTRAINT FK_ST_DOC_ITEM_SRC_LOC FOREIGN KEY (SOURCE_LOCATION_ID) REFERENCES STORAGE_LOCATION (ID);

/* STOCK_DOCUMENT_ITEM.FK_ST_DOC_ITEM_TRG_LOC */
ALTER TABLE STOCK_DOCUMENT_ITEM
ADD CONSTRAINT FK_ST_DOC_ITEM_TRG_LOC FOREIGN KEY (TARGET_LOCATION_ID) REFERENCES STORAGE_LOCATION (ID);

/* PRODUCT_CATEGORY.FK_PRODUCT_CATEGORY_PARENT */
ALTER TABLE PRODUCT_CATEGORY
ADD CONSTRAINT FK_PRODUCT_CATEGORY_PARENT FOREIGN KEY (PARENT_ID) REFERENCES PRODUCT_CATEGORY (ID);

/* STORAGE_LOCATION.FK_ST_LOC_WAREHOUSE */
ALTER TABLE STORAGE_LOCATION
ADD CONSTRAINT FK_ST_LOC_WAREHOUSE FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE (ID);

/* STOCK_DOCUMENT.FK_STOCK_DOC_PARTY */
ALTER TABLE STOCK_DOCUMENT
ADD CONSTRAINT FK_STOCK_DOC_PARTY FOREIGN KEY (COUNTERPARTY_ID) REFERENCES COUNTERPARTY (ID);

/* STOCK_DOCUMENT.FK_STOCK_DOC_USER */
ALTER TABLE STOCK_DOCUMENT
ADD CONSTRAINT FK_STOCK_DOC_USER FOREIGN KEY (CREATED_BY) REFERENCES APP_USER (ID);

/* STOCK_DOCUMENT.FK_STOCK_DOC_WAREHOUSE */
ALTER TABLE STOCK_DOCUMENT
ADD CONSTRAINT FK_STOCK_DOC_WAREHOUSE FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE (ID);

/* APP_USER.FK_APP_USER_ROLE */
ALTER TABLE APP_USER
ADD CONSTRAINT FK_APP_USER_ROLE FOREIGN KEY (ROLE_ID) REFERENCES APP_ROLE (ID);

/* WAREHOUSE.CHK_WAREHOUSE_ACTIVE */
ALTER TABLE WAREHOUSE
ADD CONSTRAINT CHK_WAREHOUSE_ACTIVE CHECK (IS_ACTIVE IN (0, 1));

/* PRODUCT.CHK_PRODUCT_ACTIVE */
ALTER TABLE PRODUCT
ADD CONSTRAINT CHK_PRODUCT_ACTIVE CHECK (IS_ACTIVE IN (0, 1));

/* PRODUCT.CHK_PRODUCT_MIN_STOCK */
ALTER TABLE PRODUCT
ADD CONSTRAINT CHK_PRODUCT_MIN_STOCK CHECK (MIN_STOCK >= 0);

/* PRODUCT.CHK_PRODUCT_PRICE */
ALTER TABLE PRODUCT
ADD CONSTRAINT CHK_PRODUCT_PRICE CHECK (PRICE >= 0);

/* STOCK_DOCUMENT_ITEM.CHK_ST_DOC_ITEM_DIFF */
ALTER TABLE STOCK_DOCUMENT_ITEM
ADD CONSTRAINT CHK_ST_DOC_ITEM_DIFF CHECK (
        SOURCE_LOCATION_ID IS NULL
        OR TARGET_LOCATION_ID IS NULL
        OR SOURCE_LOCATION_ID <> TARGET_LOCATION_ID
    );

/* STOCK_DOCUMENT_ITEM.CHK_ST_DOC_ITEM_LOC */
ALTER TABLE STOCK_DOCUMENT_ITEM
ADD CONSTRAINT CHK_ST_DOC_ITEM_LOC CHECK (
        SOURCE_LOCATION_ID IS NOT NULL OR TARGET_LOCATION_ID IS NOT NULL
    );

/* STOCK_DOCUMENT_ITEM.CHK_ST_DOC_ITEM_PRICE */
ALTER TABLE STOCK_DOCUMENT_ITEM
ADD CONSTRAINT CHK_ST_DOC_ITEM_PRICE CHECK (PRICE >= 0);

/* STOCK_DOCUMENT_ITEM.CHK_ST_DOC_ITEM_QTY */
ALTER TABLE STOCK_DOCUMENT_ITEM
ADD CONSTRAINT CHK_ST_DOC_ITEM_QTY CHECK (QUANTITY > 0);

/* COUNTERPARTY.CHK_COUNTERPARTY_ACTIVE */
ALTER TABLE COUNTERPARTY
ADD CONSTRAINT CHK_COUNTERPARTY_ACTIVE CHECK (IS_ACTIVE IN (0, 1));

/* COUNTERPARTY.CHK_COUNTERPARTY_TYPE */
ALTER TABLE COUNTERPARTY
ADD CONSTRAINT CHK_COUNTERPARTY_TYPE CHECK (PARTY_TYPE IN ('SUPPLIER', 'CUSTOMER', 'BOTH'));

/* STORAGE_LOCATION.CHK_ST_LOC_ACTIVE */
ALTER TABLE STORAGE_LOCATION
ADD CONSTRAINT CHK_ST_LOC_ACTIVE CHECK (IS_ACTIVE IN (0, 1));

/* STORAGE_LOCATION.CHK_ST_LOC_CAPACITY */
ALTER TABLE STORAGE_LOCATION
ADD CONSTRAINT CHK_ST_LOC_CAPACITY CHECK (CAPACITY IS NULL OR CAPACITY >= 0);

/* STOCK_DOCUMENT.CHK_STOCK_DOC_STATUS */
ALTER TABLE STOCK_DOCUMENT
ADD CONSTRAINT CHK_STOCK_DOC_STATUS CHECK (DOC_STATUS IN ('DRAFT', 'POSTED', 'CANCELLED'));

/* STOCK_DOCUMENT.CHK_STOCK_DOC_TYPE */
ALTER TABLE STOCK_DOCUMENT
ADD CONSTRAINT CHK_STOCK_DOC_TYPE CHECK (DOC_TYPE IN ('IN', 'OUT', 'MOVE', 'ADJUSTMENT'));

/* APP_USER.CHK_APP_USER_ACTIVE */
ALTER TABLE APP_USER
ADD CONSTRAINT CHK_APP_USER_ACTIVE CHECK (IS_ACTIVE IN (0, 1));

