spring.application.name=sklad-system
server.port=8080
spring.datasource.url=jdbc:firebird://localhost:3050//var/lib/firebird/data/sklad-system/sklad_system.fdb
spring.datasource.username=SYSDBA
spring.datasource.password=7517

spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.FirebirdDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true